version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
  deploy:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "86:64:9f:b6:c5:c7:40:dd:81:23:4b:27:63:30:f9:2a"
      - run:
          name: Deploying
          command: |
            ssh root@202.182.107.46 'cd /var/app/proxy/; git reset --hard; git pull --rebase; bash ./deploy.sh'

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
