debug = true

logLevel = "ERROR"
defaultEntryPoints = ["https","http"]


[entryPoints]
  [entryPoints.http]
  address = ":80"
    # [entryPoints.http.redirect]
    # entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]
  [entryPoints.dashboard]
    address=":8080"

[api]
entrypoint = "dashboard"

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "yuyuko.me"
watch = true
exposedByDefault = true

[acme]
email = "yuyuko@yuyuko.me"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
[acme.httpChallenge]
entryPoint = "http"
